// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectGaia.Server.Data;

#nullable disable

namespace ProjectGaia.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250130195825_CurrentMigration")]
    partial class CurrentMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectGaia.Server.Models.AccessLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AccountID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("AccountID");

                    b.ToTable("AccessLogs", (string)null);
                });

            modelBuilder.Entity("ProjectGaia.Server.Models.Account", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Accounts", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Email = "Admin0@gmail.com",
                            Name = "Admin Zero",
                            Password = new byte[] { 247, 29, 251, 37, 229, 79, 87, 173, 203, 118, 106, 6, 27, 122, 61, 92, 47, 129, 199, 213, 132, 30, 15, 48, 225, 44, 65, 100, 237, 61, 145, 253 },
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            ID = 2,
                            Email = "Admin1@gmail.com",
                            Name = "Admin One",
                            Password = new byte[] { 47, 71, 65, 19, 18, 3, 186, 233, 46, 141, 163, 36, 76, 229, 140, 187, 140, 197, 118, 181, 178, 58, 231, 52, 75, 160, 190, 23, 148, 68, 240, 76 },
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            ID = 3,
                            Email = "User0@gmail.com",
                            Name = "User Zero",
                            Password = new byte[] { 174, 189, 228, 229, 148, 10, 6, 101, 193, 44, 194, 80, 93, 44, 201, 123, 198, 131, 130, 47, 90, 195, 11, 203, 62, 147, 230, 151, 81, 26, 2, 6 },
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            ID = 4,
                            Email = "User1@gmail.com",
                            Name = "User One",
                            Password = new byte[] { 98, 67, 122, 103, 110, 207, 70, 228, 253, 179, 10, 45, 140, 113, 234, 30, 125, 201, 126, 31, 172, 234, 96, 222, 220, 174, 216, 30, 88, 42, 183, 192 },
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            ID = 5,
                            Email = "User2@gmail.com",
                            Name = "User Two",
                            Password = new byte[] { 102, 128, 196, 211, 221, 116, 187, 125, 117, 37, 99, 136, 180, 215, 228, 98, 85, 207, 81, 185, 127, 182, 55, 168, 2, 68, 191, 51, 64, 215, 80, 236 },
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            ID = 6,
                            Email = "User3@gmail.com",
                            Name = "User Three",
                            Password = new byte[] { 180, 219, 17, 148, 40, 54, 29, 85, 38, 187, 213, 122, 249, 23, 215, 100, 124, 107, 147, 25, 205, 67, 144, 19, 13, 169, 103, 180, 11, 115, 1, 176 },
                            Status = 1,
                            Type = 0
                        },
                        new
                        {
                            ID = 7,
                            Email = "User4@gmail.com",
                            Name = "User Four",
                            Password = new byte[] { 72, 4, 248, 39, 87, 27, 96, 64, 217, 166, 186, 70, 149, 133, 141, 129, 64, 102, 178, 253, 129, 107, 142, 145, 89, 79, 126, 172, 169, 185, 102, 22 },
                            Status = 1,
                            Type = 0
                        });
                });

            modelBuilder.Entity("ProjectGaia.Server.Models.ErrorLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AccountID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AccountID");

                    b.ToTable("ErrorLogs", (string)null);
                });

            modelBuilder.Entity("ProjectGaia.Server.Models.Invoice", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AccountID")
                        .HasColumnType("int");

                    b.Property<decimal>("Consumption")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("AccountID");

                    b.ToTable("Invoices", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AccountID = 3,
                            Consumption = 2m,
                            EmissionDate = new DateTime(2025, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 3m,
                            UploadDate = new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ProjectGaia.Server.Models.Session", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AccountID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("AccountID");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("Sessions", (string)null);

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AccountID = 3,
                            Expiration = new DateTime(2025, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Token = "B+RuP8JimIAmX/6/iN/VJDJko2bOcJMMSIOuesKn384="
                        },
                        new
                        {
                            ID = 2,
                            AccountID = 4,
                            Expiration = new DateTime(2025, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Token = "7f3YlmAyhNHm1MTXCSUiFNbRfb8+PNUSfj3Fb0vCrvY="
                        },
                        new
                        {
                            ID = 3,
                            AccountID = 5,
                            Expiration = new DateTime(2025, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Token = "x1bTdbciDgLLY67E4by8tv9UaVOgNqkfyBFIIB9GIBM="
                        });
                });

            modelBuilder.Entity("ProjectGaia.Server.Models.AccessLog", b =>
                {
                    b.HasOne("ProjectGaia.Server.Models.Account", "Account")
                        .WithMany("AccessLogs")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ProjectGaia.Server.Models.ErrorLog", b =>
                {
                    b.HasOne("ProjectGaia.Server.Models.Account", "Account")
                        .WithMany("ErrorLogs")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ProjectGaia.Server.Models.Invoice", b =>
                {
                    b.HasOne("ProjectGaia.Server.Models.Account", "Account")
                        .WithMany("Invoices")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ProjectGaia.Server.Models.Session", b =>
                {
                    b.HasOne("ProjectGaia.Server.Models.Account", "Account")
                        .WithMany("Sessions")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ProjectGaia.Server.Models.Account", b =>
                {
                    b.Navigation("AccessLogs");

                    b.Navigation("ErrorLogs");

                    b.Navigation("Invoices");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
