// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectGaia.Server.Data;

#nullable disable

namespace ProjectGaia.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250113231232_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectGaia.Server.Models.AccessLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AccountID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("AccountID");

                    b.ToTable("AccessLogs");
                });

            modelBuilder.Entity("ProjectGaia.Server.Models.Account", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Email = "patientzero@gmail.com",
                            Name = "Patient Zero",
                            Password = new byte[0],
                            Status = 0,
                            Type = 1
                        },
                        new
                        {
                            ID = 2,
                            Email = "patientone@gmail.com",
                            Name = "Patient One",
                            Password = new byte[0],
                            Status = 1,
                            Type = 1
                        },
                        new
                        {
                            ID = 3,
                            Email = "userzero@gmail.com",
                            Name = "User Zero",
                            Password = new byte[0],
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            ID = 4,
                            Email = "userone@gmail.com",
                            Name = "User One",
                            Password = new byte[0],
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            ID = 5,
                            Email = "usertwo@gmail.com",
                            Name = "User Two",
                            Password = new byte[0],
                            Status = 0,
                            Type = 0
                        },
                        new
                        {
                            ID = 6,
                            Email = "userthree@gmail.com",
                            Name = "User Three",
                            Password = new byte[0],
                            Status = 1,
                            Type = 0
                        },
                        new
                        {
                            ID = 7,
                            Email = "userfour@gmail.com",
                            Name = "User Four",
                            Password = new byte[0],
                            Status = 1,
                            Type = 0
                        });
                });

            modelBuilder.Entity("ProjectGaia.Server.Models.ErrorLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AccountID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AccountID");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("ProjectGaia.Server.Models.Session", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AccountID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("AccountID");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("ProjectGaia.Server.Models.AccessLog", b =>
                {
                    b.HasOne("ProjectGaia.Server.Models.Account", "Account")
                        .WithMany("AccessLogs")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ProjectGaia.Server.Models.ErrorLog", b =>
                {
                    b.HasOne("ProjectGaia.Server.Models.Account", "Account")
                        .WithMany("ErrorLogs")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ProjectGaia.Server.Models.Session", b =>
                {
                    b.HasOne("ProjectGaia.Server.Models.Account", "Account")
                        .WithMany("Sessions")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ProjectGaia.Server.Models.Account", b =>
                {
                    b.Navigation("AccessLogs");

                    b.Navigation("ErrorLogs");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
