name: Run Tests

on:
  push:
    branches:
      - main  # Trigger this workflow when commits are pushed to the 'main' branch

jobs:
  test:
    runs-on: windows-latest  # Use Windows environment for the tests

    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest  # Use the SQL Server Docker image
        env:
          SA_PASSWORD: ${{ secrets.SA_PASSWORD }}  # Get the SQL Server password from GitHub Secrets
          ACCEPT_EULA: "Y"  # Accept the SQL Server license agreement
        ports:
          - 1433:1433  # Expose SQL Server port

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Checkout the repository to the GitHub runner

      - name: Set up .NET
        uses: actions/setup-dotnet@v3  # Set up .NET SDK
        with:
          dotnet-version: 8.0.x  # Use the required .NET version

      - name: Restore dependencies
        run: dotnet restore  # Restore the project's dependencies

      - name: Build the project
        run: dotnet build  # Build the project

      - name: Run tests
        env:
          GITHUB_ACTIONS: true  # Explicitly set the GitHub Actions environment variable
          SA_PASSWORD: ${{ secrets.SA_PASSWORD }}
        run: dotnet test  # Run the tests
